[2025-10-04T13:39:05.309+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-04T13:39:05.370+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Airflow_Depi.Random_Number scheduled__2025-10-04T13:38:00+00:00 [queued]>
[2025-10-04T13:39:05.389+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Airflow_Depi.Random_Number scheduled__2025-10-04T13:38:00+00:00 [queued]>
[2025-10-04T13:39:05.391+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-10-04T13:39:05.424+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): Random_Number> on 2025-10-04 13:38:00+00:00
[2025-10-04T13:39:05.452+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=59) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-04T13:39:05.460+0000] {standard_task_runner.py:63} INFO - Started process 61 to run task
[2025-10-04T13:39:05.458+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Airflow_Depi', 'Random_Number', 'scheduled__2025-10-04T13:38:00+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/dag1.py', '--cfg-path', '/tmp/tmpp7cld7l6']
[2025-10-04T13:39:05.464+0000] {standard_task_runner.py:91} INFO - Job 66: Subtask Random_Number
[2025-10-04T13:39:05.500+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-10-04T13:39:05.656+0000] {task_command.py:426} INFO - Running <TaskInstance: Airflow_Depi.Random_Number scheduled__2025-10-04T13:38:00+00:00 [running]> on host 988bb18cf3ec
[2025-10-04T13:39:05.956+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Airflow_Depi' AIRFLOW_CTX_TASK_ID='Random_Number' AIRFLOW_CTX_EXECUTION_DATE='2025-10-04T13:38:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-04T13:38:00+00:00'
[2025-10-04T13:39:05.964+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-04T13:39:05.966+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-04T13:39:05.969+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag1.py", line 6, in random_number
    print(random.randint())
          ^^^^^^^^^^^^^^^^
TypeError: Random.randint() missing 2 required positional arguments: 'a' and 'b'
[2025-10-04T13:39:06.010+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Airflow_Depi, task_id=Random_Number, run_id=scheduled__2025-10-04T13:38:00+00:00, execution_date=20251004T133800, start_date=20251004T133905, end_date=20251004T133906
[2025-10-04T13:39:06.060+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 66 for task Random_Number (Random.randint() missing 2 required positional arguments: 'a' and 'b'; 61)
[2025-10-04T13:39:06.121+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-04T13:39:06.176+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-04T13:39:06.182+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
