[2025-10-04T13:40:05.414+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-04T13:40:05.530+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Airflow_Depi.Random_Number scheduled__2025-10-04T13:39:00+00:00 [queued]>
[2025-10-04T13:40:05.583+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Airflow_Depi.Random_Number scheduled__2025-10-04T13:39:00+00:00 [queued]>
[2025-10-04T13:40:05.584+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-10-04T13:40:05.657+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): Random_Number> on 2025-10-04 13:39:00+00:00
[2025-10-04T13:40:05.679+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=62) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-04T13:40:05.686+0000] {standard_task_runner.py:63} INFO - Started process 64 to run task
[2025-10-04T13:40:05.685+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Airflow_Depi', 'Random_Number', 'scheduled__2025-10-04T13:39:00+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/dag1.py', '--cfg-path', '/tmp/tmp4ezp96dd']
[2025-10-04T13:40:05.693+0000] {standard_task_runner.py:91} INFO - Job 67: Subtask Random_Number
[2025-10-04T13:40:05.726+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-10-04T13:40:05.870+0000] {task_command.py:426} INFO - Running <TaskInstance: Airflow_Depi.Random_Number scheduled__2025-10-04T13:39:00+00:00 [running]> on host 988bb18cf3ec
[2025-10-04T13:40:06.250+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Airflow_Depi' AIRFLOW_CTX_TASK_ID='Random_Number' AIRFLOW_CTX_EXECUTION_DATE='2025-10-04T13:39:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-04T13:39:00+00:00'
[2025-10-04T13:40:06.263+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-04T13:40:06.267+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-04T13:40:06.271+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag1.py", line 6, in random_number
    #     print(random.randint())
              ^^^^^^^^^^^^^^^^
TypeError: Random.randint() missing 2 required positional arguments: 'a' and 'b'
[2025-10-04T13:40:06.327+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Airflow_Depi, task_id=Random_Number, run_id=scheduled__2025-10-04T13:39:00+00:00, execution_date=20251004T133900, start_date=20251004T134005, end_date=20251004T134006
[2025-10-04T13:40:06.373+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 67 for task Random_Number (Random.randint() missing 2 required positional arguments: 'a' and 'b'; 64)
[2025-10-04T13:40:06.429+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-04T13:40:06.464+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-04T13:40:06.469+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
